Assembler: ProjectMain.o The_Passages.o First_Passage.o Second_Passage.o SecondPassage_Setup.o Final_Translation.o General_Functions.o Data_Retriever.o Command_Converter.o FirstPassage_Error_Examiner.o SecondPassage_Error_Examiner.o
	gcc -g -Wall -ansi -pedantic ProjectMain.o The_Passages.o First_Passage.o Second_Passage.o SecondPassage_Setup.o Final_Translation.o General_Functions.o Data_Retriever.o Command_Converter.o FirstPassage_Error_Examiner.o SecondPassage_Error_Examiner.o -o Assembler 
ProjectMain.o: ProjectMain.c Data_File.h
	gcc -c -Wall -ansi -pedantic ProjectMain.c -o ProjectMain.o 
The_Passages.o: The_Passages.c Data_File.h
	gcc -c -Wall -ansi -pedantic The_Passages.c -o The_Passages.o
First_Passage.o: First_Passage.c Data_File.h
	gcc -c -Wall -ansi -pedantic First_Passage.c -o First_Passage.o
Second_Passage.o: Second_Passage.c Data_File.h
	gcc -c -Wall -ansi -pedantic Second_Passage.c -o Second_Passage.o
SecondPassage_Setup.o: SecondPassage_Setup.c Data_File.h
	gcc -c -Wall -ansi -pedantic SecondPassage_Setup.c -o SecondPassage_Setup.o
Final_Translation.o: Final_Translation.c Data_File.h
	gcc -c -Wall -ansi -pedantic Final_Translation.c -o Final_Translation.o
General_Functions.o: General_Functions.c Data_File.h
	gcc -c -Wall -ansi -pedantic General_Functions.c -o General_Functions.o
Data_Retriever.o: Data_Retriever.c Data_File.h
	gcc -c -Wall -ansi -pedantic Data_Retriever.c -o Data_Retriever.o 
Command_Converter.o: Command_Converter.c Data_File.h
	gcc -c -Wall -ansi -pedantic Command_Converter.c -o Command_Converter.o
FirstPassage_Error_Examiner.o: FirstPassage_Error_Examiner.c Data_File.h
	gcc -c -Wall -ansi -pedantic FirstPassage_Error_Examiner.c -o FirstPassage_Error_Examiner.o
SecondPassage_Error_Examiner.o: SecondPassage_Error_Examiner.c Data_File.h
	gcc -c -Wall -ansi -pedantic SecondPassage_Error_Examiner.c -o SecondPassage_Error_Examiner.o
